version: '{build}-{branch}'
image: Visual Studio 2017

# don't enable for charm
#clone_depth: 50


init:
- ps: |
    function craft() {
        & "C:\python36\python.exe" "C:\CraftMaster\CraftMaster\CraftMaster.py" --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 git://anongit.kde.org/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    craft craft
    craft nsis
    craft --install-deps charm

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER charm

after_build:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER --package charm

test_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER --test charm

environment:
    matrix:
    - TARGET: windows-msvc2017_32-cl
    - TARGET: windows-msvc2017_64-cl

artifacts:
  - path: cache\**\.*
  - path: binaries\*

deploy:
    - provider: Environment
      name: GammaRay
